<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE PARTSLIST [<!ELEMENT PARTSLIST (HEADER, PARTS*)>
<!ATTLIST PARTSLIST VERSIONNUMBER CDATA #REQUIRED>
<!ELEMENT HEADER (SERIALNO, ORDERID, WORKORDER, SEGMENT, JOBCODE, USERID, ADDITIONALNOTES)>
<!ELEMENT SERIALNO (#PCDATA)>
<!ELEMENT ORDERID (#PCDATA)>
<!ELEMENT WORKORDER (#PCDATA)>
<!ELEMENT SEGMENT (#PCDATA)>
<!ELEMENT JOBCODE (#PCDATA)>
<!ELEMENT USERID (#PCDATA)>
<!ELEMENT ADDITIONALNOTES (#PCDATA)>
<!ELEMENT PARTS (PART*)>
<!ELEMENT PART (PARTNO, PARTNAME, MODIFIER, QUANTITY, GROUPNO, GROUPNAME, USERNOTE, PARENTAGE?, REFERENCENO?, PARTNOTE, GRAPHICS?, SMCSCODE?, TYPE)>
<!ELEMENT PARTNO (#PCDATA)>
<!ELEMENT PARTNAME (#PCDATA)>
<!ELEMENT MODIFIER (#PCDATA)>
<!ELEMENT QUANTITY (#PCDATA)>
<!ELEMENT GROUPNO (#PCDATA)>
<!ELEMENT GROUPNAME (#PCDATA)>
<!ELEMENT USERNOTE (#PCDATA)>
<!ELEMENT PARENTAGE (#PCDATA)>
<!ELEMENT REFERENCENO (#PCDATA)>
<!ELEMENT PARTNOTE (#PCDATA)>
<!ELEMENT GRAPHICS (#PCDATA)>
<!ELEMENT SMCSCODE (#PCDATA)>
<!ELEMENT TYPE (#PCDATA)> ]>
<PARTSLIST VERSIONNUMBER="SISXML1.0"><HEADER><SERIALNO>RM500151</SERIALNO><ORDERID><![CDATA[d350RM5]]></ORDERID><WORKORDER/><SEGMENT/><JOBCODE/><USERID><![CDATA[d350]]></USERID><ADDITIONALNOTES><![CDATA[2024_12_18 992K Valves]]></ADDITIONALNOTES></HEADER><PARTS><PART><PARTNO><![CDATA[122-8863]]></PARTNO><PARTNAME><![CDATA[SENSOR GP-SPEED (MAGNETIC, LOW OUTPUT)(TRANSMISSION INPUT)]]></PARTNAME><MODIFIER><![CDATA[ (MAGNETIC, LOW OUTPUT)(TRANSMISSION INPUT)]]></MODIFIER><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[347-6862]]></GROUPNO><GROUPNAME><![CDATA[GEAR GP-INPUT TRANSFER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[8]]></REFERENCENO><PARTNOTE><![CDATA[Y]]></PARTNOTE><SMCSCODE><![CDATA[3159]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[3K-0360]]></PARTNO><PARTNAME><![CDATA[SEAL-O-RING]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[347-6862]]></GROUPNO><GROUPNAME><![CDATA[GEAR GP-INPUT TRANSFER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[23]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[3159]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[430-9448]]></PARTNO><PARTNAME><![CDATA[SENSOR GP-LIQUID LEVEL (TRANSFER CASE)]]></PARTNAME><MODIFIER><![CDATA[ (TRANSFER CASE)]]></MODIFIER><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[345-2926]]></GROUPNO><GROUPNAME><![CDATA[GEAR & CASE GP-TRANSFER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[29]]></REFERENCENO><PARTNOTE><![CDATA[Y]]></PARTNOTE><SMCSCODE><![CDATA[3159]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[318-1179]]></PARTNO><PARTNAME><![CDATA[SENSOR GP-SPEED (MAGNETIC, HIGH OUTPUT)]]></PARTNAME><MODIFIER><![CDATA[ (MAGNETIC, HIGH OUTPUT)]]></MODIFIER><QUANTITY><![CDATA[2]]></QUANTITY><GROUPNO><![CDATA[345-2926]]></GROUPNO><GROUPNAME><![CDATA[GEAR & CASE GP-TRANSFER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[30]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[3159]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[2M-9780]]></PARTNO><PARTNAME><![CDATA[SEAL-O-RING]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[345-2926]]></GROUPNO><GROUPNAME><![CDATA[GEAR & CASE GP-TRANSFER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[49]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[3159]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[3K-0360]]></PARTNO><PARTNAME><![CDATA[SEAL-O-RING]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[2]]></QUANTITY><GROUPNO><![CDATA[345-2926]]></GROUPNO><GROUPNAME><![CDATA[GEAR & CASE GP-TRANSFER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[52]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[3159]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[302-3811]]></PARTNO><PARTNAME><![CDATA[VALVE GP-SOLENOID (TRANSMISSION CLUTCH)]]></PARTNAME><MODIFIER><![CDATA[ (TRANSMISSION CLUTCH)]]></MODIFIER><QUANTITY><![CDATA[3]]></QUANTITY><GROUPNO><![CDATA[295-6904]]></GROUPNO><GROUPNAME><![CDATA[VALVE GP-TRANSMISSION CONTROL]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[13]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[3073]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[279-6528]]></PARTNO><PARTNAME><![CDATA[VALVE GP-SOLENOID (24-VOLT)(HYDRAULIC LOCKOUT)]]></PARTNAME><MODIFIER><![CDATA[ (24-VOLT)(HYDRAULIC LOCKOUT)]]></MODIFIER><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[284-6627]]></GROUPNO><GROUPNAME><![CDATA[VALVE GP-MAIN CONTROL]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[8]]></REFERENCENO><PARTNOTE><![CDATA[CY]]></PARTNOTE><SMCSCODE><![CDATA[5051]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[117-0159]]></PARTNO><PARTNAME><![CDATA[VALVE GP-RELIEF (MAIN)]]></PARTNAME><MODIFIER><![CDATA[ (MAIN)]]></MODIFIER><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[284-6630]]></GROUPNO><GROUPNAME><![CDATA[VALVE GP-CONTROL -2-FUNCTION, RH]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[10]]></REFERENCENO><PARTNOTE><![CDATA[Y]]></PARTNOTE><SMCSCODE><![CDATA[5051]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[423-7704]]></PARTNO><PARTNAME><![CDATA[VALVE GP-RELIEF (LINE, TILT)]]></PARTNAME><MODIFIER><![CDATA[ (LINE, TILT)]]></MODIFIER><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[284-6630]]></GROUPNO><GROUPNAME><![CDATA[VALVE GP-CONTROL -2-FUNCTION, RH]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[11]]></REFERENCENO><PARTNOTE><![CDATA[Y]]></PARTNOTE><SMCSCODE><![CDATA[5051]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[217-6719]]></PARTNO><PARTNAME><![CDATA[ACTUATOR GP-PILOT CONTROL (LIFT, LOWER)]]></PARTNAME><MODIFIER><![CDATA[ (LIFT, LOWER)]]></MODIFIER><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[284-6630]]></GROUPNO><GROUPNAME><![CDATA[VALVE GP-CONTROL -2-FUNCTION, RH]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[13]]></REFERENCENO><PARTNOTE><![CDATA[Y]]></PARTNOTE><SMCSCODE><![CDATA[5051]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[217-6720]]></PARTNO><PARTNAME><![CDATA[ACTUATOR GP-PILOT CONTROL (HOIST CONTROL VALVE)]]></PARTNAME><MODIFIER><![CDATA[ (HOIST CONTROL VALVE)]]></MODIFIER><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[284-6630]]></GROUPNO><GROUPNAME><![CDATA[VALVE GP-CONTROL -2-FUNCTION, RH]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[14]]></REFERENCENO><PARTNOTE><![CDATA[Y]]></PARTNOTE><SMCSCODE><![CDATA[5051]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[423-7708]]></PARTNO><PARTNAME><![CDATA[VALVE GP-RELIEF]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO/><GROUPNAME><![CDATA[VALVE GP-CONTROL]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><PARTNOTE/><TYPE/></PART><PART><PARTNO><![CDATA[423-7711]]></PARTNO><PARTNAME><![CDATA[VALVE GP-RELIEF]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO/><GROUPNAME><![CDATA[VALVE GP-CONTROL]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><PARTNOTE/><TYPE/></PART></PARTS></PARTSLIST>