<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE PARTSLIST [<!ELEMENT PARTSLIST (HEADER, PARTS*)>
<!ATTLIST PARTSLIST VERSIONNUMBER CDATA #REQUIRED>
<!ELEMENT HEADER (SERIALNO, ORDERID, WORKORDER, SEGMENT, JOBCODE, USERID, ADDITIONALNOTES)>
<!ELEMENT SERIALNO (#PCDATA)>
<!ELEMENT ORDERID (#PCDATA)>
<!ELEMENT WORKORDER (#PCDATA)>
<!ELEMENT SEGMENT (#PCDATA)>
<!ELEMENT JOBCODE (#PCDATA)>
<!ELEMENT USERID (#PCDATA)>
<!ELEMENT ADDITIONALNOTES (#PCDATA)>
<!ELEMENT PARTS (PART*)>
<!ELEMENT PART (PARTNO, PARTNAME, MODIFIER, QUANTITY, GROUPNO, GROUPNAME, USERNOTE, PARENTAGE?, REFERENCENO?, PARTNOTE, GRAPHICS?, SMCSCODE?, TYPE)>
<!ELEMENT PARTNO (#PCDATA)>
<!ELEMENT PARTNAME (#PCDATA)>
<!ELEMENT MODIFIER (#PCDATA)>
<!ELEMENT QUANTITY (#PCDATA)>
<!ELEMENT GROUPNO (#PCDATA)>
<!ELEMENT GROUPNAME (#PCDATA)>
<!ELEMENT USERNOTE (#PCDATA)>
<!ELEMENT PARENTAGE (#PCDATA)>
<!ELEMENT REFERENCENO (#PCDATA)>
<!ELEMENT PARTNOTE (#PCDATA)>
<!ELEMENT GRAPHICS (#PCDATA)>
<!ELEMENT SMCSCODE (#PCDATA)>
<!ELEMENT TYPE (#PCDATA)> ]>
<PARTSLIST VERSIONNUMBER="SISXML1.0"><HEADER><SERIALNO>RM500151</SERIALNO><ORDERID><![CDATA[d350RM5]]></ORDERID><WORKORDER/><SEGMENT/><JOBCODE/><USERID><![CDATA[d350]]></USERID><ADDITIONALNOTES><![CDATA[2024_12_18 992K Engine]]></ADDITIONALNOTES></HEADER><PARTS><PART><PARTNO><![CDATA[392-5611]]></PARTNO><PARTNAME><![CDATA[HOSE]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[339-1154]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-WATER -RADIATOR]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[1]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1380]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[346-8750]]></PARTNO><PARTNAME><![CDATA[ELBOW]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[339-1154]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-WATER -RADIATOR]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[4]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1380]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[209-4588]]></PARTNO><PARTNAME><![CDATA[CLAMP]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[4]]></QUANTITY><GROUPNO><![CDATA[339-1154]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-WATER -RADIATOR]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[5]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1380]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[209-4590]]></PARTNO><PARTNAME><![CDATA[CLAMP-T BOLT]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[4]]></QUANTITY><GROUPNO><![CDATA[339-1154]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-WATER -RADIATOR]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[6]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1380]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[372-7718]]></PARTNO><PARTNAME><![CDATA[HOSE]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[2]]></QUANTITY><GROUPNO><![CDATA[339-1154]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-WATER -RADIATOR]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[7]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1380]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[343-8888]]></PARTNO><PARTNAME><![CDATA[GASKET]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[2]]></QUANTITY><GROUPNO><![CDATA[348-1116]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-WATER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[1]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1380]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[4N-1946]]></PARTNO><PARTNAME><![CDATA[GASKET]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[348-1116]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-WATER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[2]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1380]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[4N-2199]]></PARTNO><PARTNAME><![CDATA[GASKET]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[2]]></QUANTITY><GROUPNO><![CDATA[348-1116]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-WATER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[4]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1380]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[4N-2380]]></PARTNO><PARTNAME><![CDATA[SPACER-SPECIAL]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[348-1116]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-WATER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[5]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1380]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[4N-3841]]></PARTNO><PARTNAME><![CDATA[GASKET]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[348-1116]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-WATER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[6]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1380]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[200-6410]]></PARTNO><PARTNAME><![CDATA[SEAL-O-RING]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[348-1116]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-WATER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[11]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1380]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[109-0074]]></PARTNO><PARTNAME><![CDATA[SEAL-O-RING]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[348-1116]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-WATER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[22]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1380]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[109-0075]]></PARTNO><PARTNAME><![CDATA[SEAL-O-RING]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[348-1116]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-WATER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[23]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1380]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[109-0077]]></PARTNO><PARTNAME><![CDATA[SEAL-O-RING]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[2]]></QUANTITY><GROUPNO><![CDATA[348-1116]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-WATER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[24]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1380]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[154-9023]]></PARTNO><PARTNAME><![CDATA[VALVE-SAMPLING (ENGINE COOLANT)]]></PARTNAME><MODIFIER><![CDATA[ (ENGINE COOLANT)]]></MODIFIER><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[348-1116]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-WATER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[25]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1380]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[6V-5063]]></PARTNO><PARTNAME><![CDATA[SEAL-O-RING]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[5]]></QUANTITY><GROUPNO><![CDATA[348-1116]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-WATER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[32]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1380]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[6V-5064]]></PARTNO><PARTNAME><![CDATA[SEAL-O-RING]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[2]]></QUANTITY><GROUPNO><![CDATA[348-1116]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-WATER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[33]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1380]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[6V-9027]]></PARTNO><PARTNAME><![CDATA[SEAL-O-RING]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[4]]></QUANTITY><GROUPNO><![CDATA[348-1116]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-WATER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[34]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1380]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[7C-0307]]></PARTNO><PARTNAME><![CDATA[GASKET]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[348-1116]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-WATER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[35]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1380]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[7C-0145]]></PARTNO><PARTNAME><![CDATA[CORE AS-OIL COOLER (ENGINE)(ENGINE OIL)]]></PARTNAME><MODIFIER><![CDATA[ (ENGINE)(ENGINE OIL)]]></MODIFIER><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[348-1116]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-WATER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[9]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1380]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[355-7389]]></PARTNO><PARTNAME><![CDATA[PUMP GP-WATER]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[348-4037]]></GROUPNO><GROUPNAME><![CDATA[PUMP GP-WATER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[1]]></REFERENCENO><PARTNOTE><![CDATA[Y]]></PARTNOTE><SMCSCODE><![CDATA[1361]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[9X-7371]]></PARTNO><PARTNAME><![CDATA[SEAL-O-RING]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[348-4037]]></GROUPNO><GROUPNAME><![CDATA[PUMP GP-WATER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[4]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1361]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[4N-0865]]></PARTNO><PARTNAME><![CDATA[GASKET]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[360-2377]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-ENGINE OIL FILTER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[3]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1307]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[9F-6304]]></PARTNO><PARTNAME><![CDATA[SPRING]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[2]]></QUANTITY><GROUPNO><![CDATA[360-2377]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-ENGINE OIL FILTER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[6]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1307]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[1P-1367]]></PARTNO><PARTNAME><![CDATA[PLUNGER (RELIEF VALVE)]]></PARTNAME><MODIFIER><![CDATA[ (RELIEF VALVE)]]></MODIFIER><QUANTITY><![CDATA[2]]></QUANTITY><GROUPNO><![CDATA[360-2377]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-ENGINE OIL FILTER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[7]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1307]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[378-3068]]></PARTNO><PARTNAME><![CDATA[HOSE AS]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[360-2377]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-ENGINE OIL FILTER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[8]]></REFERENCENO><PARTNOTE><![CDATA[I]]></PARTNOTE><SMCSCODE><![CDATA[1307]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[378-0575]]></PARTNO><PARTNAME><![CDATA[HOSE AS]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[360-2377]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-ENGINE OIL FILTER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[9]]></REFERENCENO><PARTNOTE><![CDATA[I]]></PARTNOTE><SMCSCODE><![CDATA[1307]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[113-5304]]></PARTNO><PARTNAME><![CDATA[SEAL-O-RING]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[3]]></QUANTITY><GROUPNO><![CDATA[360-2377]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-ENGINE OIL FILTER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[20]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1307]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[061-7540]]></PARTNO><PARTNAME><![CDATA[SEAL-O-RING]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[2]]></QUANTITY><GROUPNO><![CDATA[360-2377]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-ENGINE OIL FILTER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[21]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1307]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[5P-8068]]></PARTNO><PARTNAME><![CDATA[SEAL-O-RING]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[360-2377]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-ENGINE OIL FILTER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[23]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1307]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[112-3540]]></PARTNO><PARTNAME><![CDATA[SEAL-O-RING]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[2]]></QUANTITY><GROUPNO><![CDATA[360-2377]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-ENGINE OIL FILTER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[26]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1307]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[228-7096]]></PARTNO><PARTNAME><![CDATA[SEAL-O-RING]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[2]]></QUANTITY><GROUPNO><![CDATA[360-2377]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-ENGINE OIL FILTER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><PARTNOTE/><SMCSCODE><![CDATA[1307]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[126-2702]]></PARTNO><PARTNAME><![CDATA[SEAL-INTEGRAL]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[2]]></QUANTITY><GROUPNO><![CDATA[357-9700]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-TURBOCHARGER OIL]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[3]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1052]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[198-6068]]></PARTNO><PARTNAME><![CDATA[SEAL-INTEGRAL]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[2]]></QUANTITY><GROUPNO><![CDATA[357-9700]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-TURBOCHARGER OIL]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[4]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1052]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[228-7091]]></PARTNO><PARTNAME><![CDATA[SEAL-O-RING]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[357-9700]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-TURBOCHARGER OIL]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><PARTNOTE/><SMCSCODE><![CDATA[1052]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[238-5081]]></PARTNO><PARTNAME><![CDATA[SEAL-O-RING]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[357-9700]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-TURBOCHARGER OIL]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><PARTNOTE/><SMCSCODE><![CDATA[1052]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[238-5082]]></PARTNO><PARTNAME><![CDATA[SEAL-O-RING]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[357-9700]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-TURBOCHARGER OIL]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[12]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1052]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[228-7091]]></PARTNO><PARTNAME><![CDATA[SEAL-O-RING]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[357-9700]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-TURBOCHARGER OIL]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><PARTNOTE/><SMCSCODE><![CDATA[1052]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[238-5081]]></PARTNO><PARTNAME><![CDATA[SEAL-O-RING]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[357-9700]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-TURBOCHARGER OIL]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><PARTNOTE/><SMCSCODE><![CDATA[1052]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[8T-1117]]></PARTNO><PARTNAME><![CDATA[CLAMP-HOSE]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[4]]></QUANTITY><GROUPNO><![CDATA[357-9700]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-TURBOCHARGER OIL]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[16]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1052]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[3D-2824]]></PARTNO><PARTNAME><![CDATA[SEAL-O-RING]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[357-9700]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-TURBOCHARGER OIL]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><PARTNOTE/><SMCSCODE><![CDATA[1052]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[251-6775]]></PARTNO><PARTNAME><![CDATA[HOSE]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[2]]></QUANTITY><GROUPNO><![CDATA[357-9700]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-TURBOCHARGER OIL]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[19]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1052]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[239-1388]]></PARTNO><PARTNAME><![CDATA[GASKET]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[6]]></QUANTITY><GROUPNO><![CDATA[348-2768]]></GROUPNO><GROUPNAME><![CDATA[MANIFOLD GP-EXHAUST]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[5]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1059]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[243-3565]]></PARTNO><PARTNAME><![CDATA[SEAL-O-RING]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[4]]></QUANTITY><GROUPNO><![CDATA[348-2768]]></GROUPNO><GROUPNAME><![CDATA[MANIFOLD GP-EXHAUST]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[6]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1059]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[2N-2766]]></PARTNO><PARTNAME><![CDATA[LOCKNUT (3/8-16-THD)]]></PARTNAME><MODIFIER><![CDATA[ (3/8-16-THD)]]></MODIFIER><QUANTITY><![CDATA[12]]></QUANTITY><GROUPNO><![CDATA[348-2768]]></GROUPNO><GROUPNAME><![CDATA[MANIFOLD GP-EXHAUST]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[13]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1059]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[8N-0879]]></PARTNO><PARTNAME><![CDATA[CLAMP]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[4]]></QUANTITY><GROUPNO><![CDATA[348-2768]]></GROUPNO><GROUPNAME><![CDATA[MANIFOLD GP-EXHAUST]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[2]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1059]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[108-3612]]></PARTNO><PARTNAME><![CDATA[SPACER (11.13X19.05X53-MM THK)]]></PARTNAME><MODIFIER><![CDATA[ (11.13X19.05X53-MM THK)]]></MODIFIER><QUANTITY><![CDATA[4]]></QUANTITY><GROUPNO><![CDATA[348-2768]]></GROUPNO><GROUPNAME><![CDATA[MANIFOLD GP-EXHAUST]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[3]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1059]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[114-9223]]></PARTNO><PARTNAME><![CDATA[SPACER (11.13X19.05X19-MM THK)]]></PARTNAME><MODIFIER><![CDATA[ (11.13X19.05X19-MM THK)]]></MODIFIER><QUANTITY><![CDATA[8]]></QUANTITY><GROUPNO><![CDATA[348-2768]]></GROUPNO><GROUPNAME><![CDATA[MANIFOLD GP-EXHAUST]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[4]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1059]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[243-3566]]></PARTNO><PARTNAME><![CDATA[BELLOWS AS]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[2]]></QUANTITY><GROUPNO><![CDATA[348-2768]]></GROUPNO><GROUPNAME><![CDATA[MANIFOLD GP-EXHAUST]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[7]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1059]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[6B-2882]]></PARTNO><PARTNAME><![CDATA[SPACER (0.406X0.75X0.312-IN THK)]]></PARTNAME><MODIFIER><![CDATA[ (0.406X0.75X0.312-IN THK)]]></MODIFIER><QUANTITY><![CDATA[8]]></QUANTITY><GROUPNO><![CDATA[348-2768]]></GROUPNO><GROUPNAME><![CDATA[MANIFOLD GP-EXHAUST]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[10]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1059]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[393-5115]]></PARTNO><PARTNAME><![CDATA[STUD-TAPERLOCK (3/8-16X2.4-IN)]]></PARTNAME><MODIFIER><![CDATA[ (3/8-16X2.4-IN)]]></MODIFIER><QUANTITY><![CDATA[4]]></QUANTITY><GROUPNO><![CDATA[348-2768]]></GROUPNO><GROUPNAME><![CDATA[MANIFOLD GP-EXHAUST]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[11]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1059]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[5M-2894]]></PARTNO><PARTNAME><![CDATA[WASHER-HARD (10.2X18.5X2.5-MM THK)]]></PARTNAME><MODIFIER><![CDATA[ (10.2X18.5X2.5-MM THK)]]></MODIFIER><QUANTITY><![CDATA[12]]></QUANTITY><GROUPNO><![CDATA[348-2768]]></GROUPNO><GROUPNAME><![CDATA[MANIFOLD GP-EXHAUST]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[14]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1059]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[357-1752]]></PARTNO><PARTNAME><![CDATA[GASKET-TURBOCHARGER]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[2]]></QUANTITY><GROUPNO><![CDATA[348-2749]]></GROUPNO><GROUPNAME><![CDATA[TURBOCHARGER GP]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[1]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1052]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[284-0753]]></PARTNO><PARTNAME><![CDATA[WASHER (11X25X2.5-MM THK)]]></PARTNAME><MODIFIER><![CDATA[ (11X25X2.5-MM THK)]]></MODIFIER><QUANTITY><![CDATA[2]]></QUANTITY><GROUPNO><![CDATA[348-2749]]></GROUPNO><GROUPNAME><![CDATA[TURBOCHARGER GP]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[2]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1052]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[2N-2765]]></PARTNO><PARTNAME><![CDATA[BOLT-HIGH TEMPERATURE (3/8-16X1.75-IN)]]></PARTNAME><MODIFIER><![CDATA[ (3/8-16X1.75-IN)]]></MODIFIER><QUANTITY><![CDATA[2]]></QUANTITY><GROUPNO><![CDATA[348-2749]]></GROUPNO><GROUPNAME><![CDATA[TURBOCHARGER GP]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[5]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1052]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[2N-2766]]></PARTNO><PARTNAME><![CDATA[LOCKNUT (3/8-16-THD)]]></PARTNAME><MODIFIER><![CDATA[ (3/8-16-THD)]]></MODIFIER><QUANTITY><![CDATA[8]]></QUANTITY><GROUPNO><![CDATA[348-2749]]></GROUPNO><GROUPNAME><![CDATA[TURBOCHARGER GP]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[6]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1052]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[5P-7128]]></PARTNO><PARTNAME><![CDATA[BOLT-HIGH TEMPERATURE (3/8-16X2-IN)]]></PARTNAME><MODIFIER><![CDATA[ (3/8-16X2-IN)]]></MODIFIER><QUANTITY><![CDATA[2]]></QUANTITY><GROUPNO><![CDATA[348-2749]]></GROUPNO><GROUPNAME><![CDATA[TURBOCHARGER GP]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[7]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1052]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[302-1409]]></PARTNO><PARTNAME><![CDATA[CARTRIDGE GP-TURBOCHARGER]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[375-9396]]></GROUPNO><GROUPNAME><![CDATA[TURBOCHARGER GP]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[2]]></REFERENCENO><PARTNOTE><![CDATA[Y]]></PARTNOTE><SMCSCODE><![CDATA[1052]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[268-2960]]></PARTNO><PARTNAME><![CDATA[CLAMP AS (COMPRESSOR)]]></PARTNAME><MODIFIER><![CDATA[ (COMPRESSOR)]]></MODIFIER><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[375-9396]]></GROUPNO><GROUPNAME><![CDATA[TURBOCHARGER GP]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[3]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1052]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[9N-2038]]></PARTNO><PARTNAME><![CDATA[CLAMP AS-TURBINE]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[375-9396]]></GROUPNO><GROUPNAME><![CDATA[TURBOCHARGER GP]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[5]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1052]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[106-1792]]></PARTNO><PARTNAME><![CDATA[STUD-TAPERLOCK (3/8-16X4-IN)]]></PARTNAME><MODIFIER><![CDATA[ (3/8-16X4-IN)]]></MODIFIER><QUANTITY><![CDATA[12]]></QUANTITY><GROUPNO><![CDATA[339-3585]]></GROUPNO><GROUPNAME><![CDATA[CYLINDER HEAD GP]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[3]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1100]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[216-8579]]></PARTNO><PARTNAME><![CDATA[SEAL-O-RING]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[483-7455]]></GROUPNO><GROUPNAME><![CDATA[WIRING GP-ENGINE]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[6]]></REFERENCENO><PARTNOTE><![CDATA[C]]></PARTNOTE><SMCSCODE><![CDATA[1403]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[416-6999]]></PARTNO><PARTNAME><![CDATA[SENSOR GP-PRESSURE]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[483-7455]]></GROUPNO><GROUPNAME><![CDATA[WIRING GP-ENGINE]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[7]]></REFERENCENO><PARTNOTE><![CDATA[C]]></PARTNOTE><SMCSCODE><![CDATA[1403]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[449-9059]]></PARTNO><PARTNAME><![CDATA[SEAL]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[6]]></QUANTITY><GROUPNO><![CDATA[459-0812]]></GROUPNO><GROUPNAME><![CDATA[COVER GP-VALVE MECHANISM]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[7]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1107]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[033-6031]]></PARTNO><PARTNAME><![CDATA[SEAL-O-RING]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[2]]></QUANTITY><GROUPNO><![CDATA[459-0812]]></GROUPNO><GROUPNAME><![CDATA[COVER GP-VALVE MECHANISM]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[8]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1107]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[061-9457]]></PARTNO><PARTNAME><![CDATA[SEAL-O-RING]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[2]]></QUANTITY><GROUPNO><![CDATA[459-0812]]></GROUPNO><GROUPNAME><![CDATA[COVER GP-VALVE MECHANISM]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[12]]></REFERENCENO><PARTNOTE><![CDATA[C]]></PARTNOTE><SMCSCODE><![CDATA[1107]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[222-6456]]></PARTNO><PARTNAME><![CDATA[SEAL (VALVE COVER BASE)]]></PARTNAME><MODIFIER><![CDATA[ (VALVE COVER BASE)]]></MODIFIER><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[226-4927]]></GROUPNO><GROUPNAME><![CDATA[BASE GP-VALVE COVER & INJ HARN]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[7]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1120]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[3S-9643]]></PARTNO><PARTNAME><![CDATA[SEAL-LIP TYPE]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[2]]></QUANTITY><GROUPNO><![CDATA[379-0079]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-WATER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><PARTNOTE/><SMCSCODE><![CDATA[1380]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[279-3397]]></PARTNO><PARTNAME><![CDATA[SEAL-O-RING]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[379-0079]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-WATER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[7]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1380]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[248-5513]]></PARTNO><PARTNAME><![CDATA[REGULATOR-WATER TEMPERATURE (92-DEG C)]]></PARTNAME><MODIFIER><![CDATA[ (92-DEG C)]]></MODIFIER><QUANTITY><![CDATA[2]]></QUANTITY><GROUPNO><![CDATA[379-0079]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-WATER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[10]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1380]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[107-5769]]></PARTNO><PARTNAME><![CDATA[SEAL-O-RING]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[2]]></QUANTITY><GROUPNO><![CDATA[379-0079]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-WATER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[16]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1380]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[109-0075]]></PARTNO><PARTNAME><![CDATA[SEAL-O-RING]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[379-0079]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-WATER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[17]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1380]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[109-0076]]></PARTNO><PARTNAME><![CDATA[SEAL-O-RING]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[3]]></QUANTITY><GROUPNO><![CDATA[379-0079]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-WATER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[18]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1380]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[231-4708]]></PARTNO><PARTNAME><![CDATA[SEAL-O-RING]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[4]]></QUANTITY><GROUPNO><![CDATA[379-0079]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-WATER]]></GROUPNAME><USERNOTE/><PARENTAGE><![CDATA[0]]></PARENTAGE><REFERENCENO><![CDATA[20]]></REFERENCENO><PARTNOTE/><SMCSCODE><![CDATA[1380]]></SMCSCODE><TYPE/></PART><PART><PARTNO><![CDATA[238-5080]]></PARTNO><PARTNAME><![CDATA[SEAL-O-RING]]></PARTNAME><MODIFIER/><QUANTITY><![CDATA[1]]></QUANTITY><GROUPNO><![CDATA[379-0079]]></GROUPNO><GROUPNAME><![CDATA[LINES GP-WATER]]><